### ISSUE TITLE
Klasa LeagueTable

### ISSUE THREAD

**Issue by Maladie** [bkomoder/footballmanager#16]
-List<Team> teamsList - wszystkie zespoły w lidze
- metoda update (po każdej kolejce)

**Comment by Maladie** [comment]
@krzychu124 
Jak teraz patrzę to metoda update chyba w ogóle nie będzie potrzebna. Statsy się same aktualizują po meczu, więc drużyny niejako z automatu będą miały je aktualne, więc i tabela będzie miała. Dobrze myślę?

**Comment by krzychu124** [comment]
Dobrze myślisz, w sumie to i tak nie miałem pomysłu jaki miałby tam być parametr ;). Wywalić :)

**Comment by krzychu124** [comment]
- [x] usunąć metodę update

**Comment by krzychu124** [comment]
- [ ] sprawdzić czy liczba drużyn jest parzysta

**Comment by krzychu124** [comment]
- [x] sprawdzić czy liczba drużyn jest parzysta
