### ISSUE TITLE
Klasa Team

### ISSUE THREAD

**Issue by Maladie** [bkomoder/footballmanager#6]
- TeamStat teamStatistics
- id (random)
- LocalDate foundationDate
- name
- Tablica[11] actualTeam
- List<FP> substitutes

**Comment by Maladie** [comment]
Trzeba dodać pole klasy TeamStat

**Comment by krzychu124** [comment]
Dodałem listę wszystkich oponentów, ustawiana przy generowaniu kolejek 😃

**Comment by krzychu124** [comment]
Dodałem info/flagę - czy drużyna jest kontrolowana przez komputer
